<!-- NEW TICKET -->

## Description  
_A clear and concise description of the issue._

## User Story  
**As a** [user type],  
**I want to** [goal or task],  
**So that** [reason or benefit].  

## Engineering Checklist  
- [ ] List technical tasks required to complete the issue  
- [ ] Include API changes, database migrations, or dependencies if applicable  
- [ ] Add tests if necessary  

## Acceptance Criteria  
- [ ] Define the conditions that must be met for this issue to be considered complete  
- [ ] Specify expected behavior or outcomes  

## Relevant Logs or Screenshots  
_Paste any logs, error messages, or screenshots here._  

## Additional Context  
_Any other information that might be relevant._  
