name: Feature Request
description: Propose a new feature or improvement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for your contribution!  
        Please fill out the following details to help us evaluate your request.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the issue.
      placeholder: "Describe the problem or improvement."
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Define the user need in the following format.
      placeholder: |
        **As a** [user type],  
        **I want to** [goal or task],  
        **So that** [reason or benefit].
    validations:
      required: true

  - type: textarea
    id: engineering-checklist
    attributes:
      label: Engineering Checklist
      description: List technical tasks required to complete this issue.
      placeholder: |
        - [ ] List technical tasks  
        - [ ] API changes, database migrations, dependencies  
        - [ ] Tests if necessary  
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define conditions that must be met for this issue to be considered complete.
      placeholder: |
        - [ ] Expected behavior or outcomes  
        - [ ] Edge cases to handle  
    validations:
      required: true

  - type: textarea
    id: logs-screenshots
    attributes:
      label: Relevant Logs or Screenshots
      description: Paste any logs, error messages, or screenshots here.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be relevant.
    validations:
      required: false
